name: ws_example

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  loggy: ^2.0.3
  obs_websocket:
    path: ../
  universal_io: ^2.2.2
  web_socket_channel: ^3.0.1
  yaml: ^3.1.2

dev_dependencies:
  lints: ^5.0.0
