name: obs_websocket
version: 5.1.0+10
homepage: https://github.com/faithoflifedev/easy_obs_websocket
description: obs_websocket allows dart-based connections to the OBS (Open Broadcaster Software) plugin obs-websocket
repository: https://github.com/faithoflifedev/easy_obs_websocket

funding:
  - https://www.buymeacoffee.com/faithoflif2

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  args: ^2.5.0
  crypto: ^3.0.3
  json_annotation: ^4.9.0
  loggy: ^2.0.3
  uuid: ^4.4.0
  universal_io: ^2.2.2
  validators: ^3.0.0
  web_socket_channel: ^3.0.1
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.9
  grinder: ^0.9.5
  http: ^1.2.1
  json_serializable: ^6.8.0
  lints: ^5.0.0
  mustache_template: ^2.0.0
  path: ^1.9.0
  process_run: ^1.2.0+3
  pub_semver: ^2.1.4
  publish_tools: ^1.0.0+4
  pubspec: ^2.3.0
  test: ^1.25.5

executables:
  obs:
